[package]
name = "LootSurvivorBeasts"
version = "0.1.0"

[dependencies]
starknet = "2.1.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", rev = "05429e4" }

[scripts]
test = "scarb cairo-test"

[[target.starknet-contract]]
sierra = true
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
