[package]
name = "pixel_beasts"
version = "0.1.0"

[dependencies]
starknet = "2.7.1"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.15.1" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.15.1" }

[dev-dependencies]
cairo_test = "2.7.1"